# Python Numpy Array Slicing(:)

In [1]:
import numpy as np

In [2]:
mx = np.arange(1,17).reshape(4,4)
print(mx)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
mx1 = np.arange(17,33).reshape(4,4)
print(mx1)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [6]:
list1 = [1,2,3]
list2 = [1,2,3]
list1 + list2

[1, 2, 3, 1, 2, 3]

# concatenate()

In [9]:
np.concatenate((mx,mx1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [18]:
d =np.concatenate((mx,mx1),axis = 1)
print(d)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


# vstack()

In [12]:
np.vstack((mx,mx1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# hstack()

In [13]:
np.hstack((mx,mx1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# split()

In [19]:
np.split(d,2)

[array([[ 1,  2,  3,  4, 17, 18, 19, 20],
        [ 5,  6,  7,  8, 21, 22, 23, 24]]),
 array([[ 9, 10, 11, 12, 25, 26, 27, 28],
        [13, 14, 15, 16, 29, 30, 31, 32]])]

In [20]:
np.split(d,2, axis=1)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]